import os
path = r'C:\Users\opdlo\Desktop\dance_stage\软件工程\软件工程\DanceFlow-Android\app\src\main\java\com\danceflow\ui\screens\PostDetailScreen.kt'

lines = []
lines.append('package com.danceflow.app.ui.screens')
lines.append('')
lines.append('import androidx.compose.foundation.layout.*')
lines.append('import androidx.compose.foundation.lazy.LazyColumn')
lines.append('import androidx.compose.foundation.lazy.items')
lines.append('import androidx.compose.foundation.shape.RoundedCornerShape')
lines.append('import androidx.compose.material.icons.Icons')
lines.append('import androidx.compose.material.icons.filled.*')
lines.append('import androidx.compose.material3.*')
lines.append('import androidx.compose.runtime.*')
lines.append('import androidx.compose.ui.Alignment')
lines.append('import androidx.compose.ui.Modifier')
lines.append('import androidx.compose.ui.draw.clip')
lines.append('import androidx.compose.ui.graphics.Color')
lines.append('import androidx.compose.ui.layout.ContentScale')
lines.append('import androidx.compose.ui.text.font.FontWeight')
lines.append('import androidx.compose.ui.text.style.TextOverflow')
lines.append('import androidx.compose.ui.unit.dp')
lines.append('import androidx.compose.ui.unit.sp')
lines.append('import androidx.compose.ui.text.SpanStyle')
lines.append('import androidx.compose.ui.text.buildAnnotatedString')
lines.append('import androidx.compose.ui.text.withStyle')
lines.append('import androidx.lifecycle.viewmodel.compose.viewModel')
lines.append('import androidx.navigation.NavController')
lines.append('import coil.compose.AsyncImage')
lines.append('import com.danceflow.app.community.DetailState')
lines.append('import com.danceflow.app.community.PostDetailViewModel')
lines.append('import com.danceflow.app.ui.components.*')
lines.append('import com.danceflow.app.ui.theme.*')
lines.append('')

with open(path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
    f.write('\n')
print('Imports written')
